### ISSUE TITLE
Using uuid@2 has unintended consequences and test failures.

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-auth-db-mem#23]
The npm story for uuid is a bit unclear, with two almost the same, but not, npm names and git repos. The sole maintainer of node-uuid is listed as a maintainer of uuid.

Anyways, a key difference between 1.4 and 2.0 in the package we use (`uuid`) is that `uuid.v4('binary')` returned a Buffer in 1.4, but returns a simple Array in 2.0, so `.toString('hex')` is a hex-string in 1.4.x, but just the integers concatendated in 2.x. https://github.com/defunctzombie/node-uuid/commit/1f44de46e2effdfdc3b6f75aae97b17401e10982

https://www.npmjs.com/package/uuid      (current version 2.0.1)
  - from github.com/shtylman/node-uuid, which redirects to https://github.com/defunctzombie/node-uuid

https://www.npmjs.com/package/node-uuid (current version 1.4.3)
  - from https://github.com/broofa/node-uuid

So, in refreshing the shrinkwrap, `npm` was reporting an extraneaous uuid@1.4.1 and wouldn't shrinkwrap without doing `npm prune`. So, did that, aaand... tests started failing because uuid@2 started being used.

Now most of the tests still passed despite the uuid change. It was really just this set of tests https://github.com/mozilla/fxa-auth-db-server/blob/master/test/backend/db_tests.js#L457-L471 that failed, because of this conversion https://github.com/mozilla/fxa-auth-db-server/blob/master/test/backend/db_tests.js#L464 (which is effectively a no-op with uuid@1.4, but matters with Array values in uuid@2).

Anyways, I'll add a PR to have fxa-auth-db-mem use uuid@1.4.1, which is what other fxa-auth-* use.

Probably should figure out whether we want to find the right choice for 'uuid' in the future, should fix the test above to not do the cast, and probably need to add tests to assert the properties of `uuid.v4("binary")' values that we rely on.

**Comment by jrgm** [comment]
@chilts to look into using node-uuid instead.

**Comment by chilts** [comment]
PR for the db-server here : https://github.com/mozilla/fxa-auth-db-server/pull/135

This PR forthcoming once that is merged (so I can re-do shrinkwrap properly) and to remove uuid@2 from db-mysql as well.

**Comment by chilts** [comment]
Ah yes, I remember now why I left the (old `uuid`) new `node-uuid` dependency in the db-mem and db-mysql repos.

The tests are contained in the db-server repo and used by the db-mem and db-mysql repos, so when the `fxa-auth-db-server/test/backend/db_tests.js` call `require('node-uuid')` it fails. The reason it fails is because the db-server lists it in the `devDependencies`. This would usually be normal and make sense.

However, since the db-server is `npm install`ed by the two backend repos, only it's production dependencies are installed and it's devDependencies aren't. Therefore, `npm test` won't work in the backend repos.

This can be fixed in a couple of ways:

1. install node-uuid in both db-mem and db-mysql (the current solution) as a devDependency
2. install node-uuid as a real dependency in db-server (unused in production, only in tests)

Both solutions have their pros and cons. Leaning towards suggestion 2 - see comment below.

(Note: I think this issue is fixed by https://github.com/mozilla/fxa-auth-db-server/pull/135 in the db-server, but this comment addresses the concerns over https://github.com/mozilla/fxa-auth-db-mem/pull/24 as to why uuid was required in both the db-mem and db-mysql repos. Perhaps therefore we go with solution 2 above, and not 1 as it currently is.)

**Comment by chilts** [comment]
If we do https://github.com/mozilla/fxa-auth-db-server/pull/136 I think that this issue here will go away.
